[package]
name = "ufos_rust"
version = "0.1.0"
authors = ["Colette ğŸŒ©ï¸â€ğŸ’ Kerr <Colette.m.y.Kerr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# userfaultfd = "0.2.0" # requires libclang1 installed
#userfaultfd = { git = "https://github.com/electroCutie/userfaultfd-rs", branch = "readwrite_fix" }
anyhow = "1.0.38"
blake3 = "0.3.7"
crossbeam = "0.8.0"
libc = "0.2.80"
log = "0.4.14"
nix = "0.17"
num = "0.3.1" # for One
segment-map = "0.1.1" # for maps over ranges
promissory = { git = "https://github.com/electroCutie/promissory", branch = "main" }
userfaultfd = { path = "/home/ckerr/workspace/userfaultfd-rs/" }

stderrlog = "0.5.1"

[build]
target_os = "linux"

