[package]
name = "ufos_rust"
version = "0.1.0"
authors = ["Colette ğŸŒ©ï¸â€ğŸ’ Kerr <Colette.m.y.Kerr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
userfaultfd = "0.2.0" # requires libclang1 installed
libc = "0.2.80"
segment-map = "0.1.1" # for maps over ranges
blake3 = "0.3.7"
num = "0.3.1"

[build]
target_os = "linux"